

const CentralHub = {
    CompaniesData: [
        {
            "id": 1,
            "name": "TechNova Solutions",
            "industry": "Information Technology",
            "founded": 2015,
            "employees": 250,
            "headquarters": { "city": "Bengaluru", "country": "India" },
            "contact": { "email": "info@technova.com", "phone": "+91-80-23456789" },
            "services": ["Web Development", "Cloud Engineering", "AI Solutions"],
            "website": "https://www.technova.com",
            "image": "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 2,
            "name": "GreenLeaf Energy",
            "industry": "Renewable Energy",
            "founded": 2012,
            "employees": 140,
            "headquarters": { "city": "Austin", "country": "USA" },
            "contact": { "email": "contact@greenleafenergy.com", "phone": "+1-512-555-0142" },
            "services": ["Solar PV", "Wind Projects", "Energy Consulting"],
            "website": "https://www.greenleafenergy.com",
            "image": "https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 3,
            "name": "UrbanBuild Constructions",
            "industry": "Construction",
            "founded": 2008,
            "employees": 600,
            "headquarters": { "city": "Dubai", "country": "UAE" },
            "contact": { "email": "projects@urbanbuild.ae", "phone": "+971-4-555-0103" },
            "services": ["Residential", "Commercial", "Infrastructure"],
            "website": "https://www.urbanbuild.ae",
            "image": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 4,
            "name": "AquaPure Systems",
            "industry": "Water Technology",
            "founded": 2017,
            "employees": 82,
            "headquarters": { "city": "Chennai", "country": "India" },
            "contact": { "email": "support@aquapure.in", "phone": "+91-44-28330111" },
            "services": ["Water Filtration", "Wastewater Treatment", "RO Solutions"],
            "website": "https://www.aquapure.in",
            "image": "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 40,
            "name": "ArcticBio Research",
            "industry": "Environmental Science",
            "founded": 2018,
            "employees": 85,
            "headquarters": { "city": "Oslo", "country": "Norway" },
            "contact": { "email": "info@arcticbio.no", "phone": "+47-21-555-8899" },
            "services": ["Climate Studies", "Eco Research", "Conservation Data"],
            "website": "https://www.arcticbio.no",
            "image": "https://images.unsplash.com/photo-1553514029-1318c9127859?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 41,
            "name": "Solarix Energy",
            "industry": "Renewable Energy",
            "founded": 2016,
            "employees": 190,
            "headquarters": { "city": "Lisbon", "country": "Portugal" },
            "contact": { "email": "contact@solarix.pt", "phone": "+351-21-555-1022" },
            "services": ["Solar Farms", "Battery Storage", "Energy Management"],
            "website": "https://www.solarix.pt",
            "image": "https://images.unsplash.com/photo-1509395062183-67c5ad6faff9?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 42,
            "name": "AeroLift Drones",
            "industry": "Aerospace",
            "founded": 2018,
            "employees": 85,
            "headquarters": { "city": "Berlin", "country": "Germany" },
            "contact": { "email": "support@aerolift.de", "phone": "+49-30-555-1133" },
            "services": ["Drone Manufacturing", "Aerial Surveys", "Delivery Drones"],
            "website": "https://www.aerolift.de",
            "image": "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 43,
            "name": "BrightPath Education",
            "industry": "Education Technology",
            "founded": 2014,
            "employees": 140,
            "headquarters": { "city": "New Delhi", "country": "India" },
            "contact": { "email": "hello@brightpath.in", "phone": "+91-11-24456789" },
            "services": ["E-Learning", "Assessment Tools", "AI Tutoring"],
            "website": "https://www.brightpath.in",
            "image": "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 44,
            "name": "DataCore Systems",
            "industry": "Software Development",
            "founded": 2009,
            "employees": 220,
            "headquarters": { "city": "Warsaw", "country": "Poland" },
            "contact": { "email": "info@datacore.pl", "phone": "+48-22-555-2010" },
            "services": ["Enterprise Software", "System Integration", "Data Engineering"],
            "website": "https://www.datacore.pl",
            "image": "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 45,
            "name": "MobiWave Networks",
            "industry": "Telecommunications",
            "founded": 2012,
            "employees": 480,
            "headquarters": { "city": "Kuala Lumpur", "country": "Malaysia" },
            "contact": { "email": "info@mobiwave.my", "phone": "+60-3-555-7777" },
            "services": ["5G Networks", "IoT Connectivity", "Network Consulting"],
            "website": "https://www.mobiwave.my",
            "image": "https://images.unsplash.com/photo-1525182008055-f88b95ff7980?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 46,
            "name": "PureFoods Organics",
            "industry": "Food & Beverages",
            "founded": 2015,
            "employees": 130,
            "headquarters": { "city": "Auckland", "country": "New Zealand" },
            "contact": { "email": "support@purefoods.co.nz", "phone": "+64-9-555-9988" },
            "services": ["Organic Foods", "Cold-Pressed Juices", "Export Services"],
            "website": "https://www.purefoods.co.nz",
            "image": "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 47,
            "name": "OmniTrade Commerce",
            "industry": "E-commerce",
            "founded": 2013,
            "employees": 380,
            "headquarters": { "city": "London", "country": "UK" },
            "contact": { "email": "sales@omnitrade.co.uk", "phone": "+44-20-555-9988" },
            "services": ["Online Retail", "Dropshipping", "Marketplace Management"],
            "website": "https://www.omnitrade.co.uk",
            "image": "https://images.unsplash.com/photo-1556742400-b5b7c5121f1d?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 5,
            "name": "MediCore Health",
            "industry": "Healthcare",
            "founded": 2010,
            "employees": 410,
            "headquarters": { "city": "Toronto", "country": "Canada" },
            "contact": { "email": "hello@medicorehealth.ca", "phone": "+1-416-555-0199" },
            "services": ["Medical Devices", "Telemedicine", "Healthcare Analytics"],
            "website": "https://www.medicorehealth.ca",
            "image": "https://images.unsplash.com/photo-1580281657521-54e65a69d6b1?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 6,
            "name": "BlueHarbor Logistics",
            "industry": "Logistics & Supply Chain",
            "founded": 2005,
            "employees": 1200,
            "headquarters": { "city": "Singapore", "country": "Singapore" },
            "contact": { "email": "ops@blueharbor.sg", "phone": "+65-6222-3344" },
            "services": ["Freight Forwarding", "Warehousing", "Last-mile Delivery"],
            "website": "https://www.blueharbor.sg",
            "image": "https://images.unsplash.com/photo-1565614192428-430b8f9a6c22?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 7,
            "name": "FinCrest Analytics",
            "industry": "Financial Services",
            "founded": 2018,
            "employees": 95,
            "headquarters": { "city": "London", "country": "UK" },
            "contact": { "email": "contact@fincrest.co.uk", "phone": "+44-20-7946-0912" },
            "services": ["Risk Modeling", "Portfolio Analytics", "Fintech APIs"],
            "website": "https://www.fincrest.co.uk",
            "image": "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 8,
            "name": "FarmSense AgriTech",
            "industry": "Agriculture Technology",
            "founded": 2016,
            "employees": 48,
            "headquarters": { "city": "Nairobi", "country": "Kenya" },
            "contact": { "email": "info@farmsense.africa", "phone": "+254-20-5550123" },
            "services": ["IoT Sensors", "Crop Analytics", "Precision Farming"],
            "website": "https://www.farmsense.africa",
            "image": "https://images.unsplash.com/photo-1500937386664-56f0e28fbbd1?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 9,
            "name": "Aurora Media Labs",
            "industry": "Media & Entertainment",
            "founded": 2013,
            "employees": 210,
            "headquarters": { "city": "Los Angeles", "country": "USA" },
            "contact": { "email": "studio@auroramedia.com", "phone": "+1-310-555-0267" },
            "services": ["Video Production", "Post-Production", "Content Strategy"],
            "website": "https://www.auroramedia.com",
            "image": "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 10,
            "name": "SecureGate Cyber",
            "industry": "Cybersecurity",
            "founded": 2014,
            "employees": 160,
            "headquarters": { "city": "Tel Aviv", "country": "Israel" },
            "contact": { "email": "security@securegate.io", "phone": "+972-3-555-1212" },
            "services": ["Penetration Testing", "SOC-as-a-Service", "Threat Intelligence"],
            "website": "https://www.securegate.io",
            "image": "https://images.unsplash.com/photo-1556155092-490a1ba16284?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 11,
            "name": "SkyLink Aerospace",
            "industry": "Aerospace & Defense",
            "founded": 2011,
            "employees": 480,
            "headquarters": { "city": "Seattle", "country": "USA" },
            "contact": { "email": "info@skylinkaero.com", "phone": "+1-206-555-4412" },
            "services": ["Drone Manufacturing", "Defense Systems", "Satellite Communications"],
            "website": "https://www.skylinkaero.com",
            "image": "https://images.unsplash.com/photo-1581090465189-1e7b6e7e69b8?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 12,
            "name": "EduVerse Learning",
            "industry": "EdTech",
            "founded": 2019,
            "employees": 120,
            "headquarters": { "city": "Pune", "country": "India" },
            "contact": { "email": "hello@eduverse.in", "phone": "+91-20-55566777" },
            "services": ["Online Learning", "Virtual Classrooms", "Skill Certification"],
            "website": "https://www.eduverse.in",
            "image": "https://images.unsplash.com/photo-1600195077909-bdb5f9e1c6d6?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 13,
            "name": "ByteForge Systems",
            "industry": "Software Development",
            "founded": 2009,
            "employees": 350,
            "headquarters": { "city": "Berlin", "country": "Germany" },
            "contact": { "email": "contact@byteforge.de", "phone": "+49-30-555-8888" },
            "services": ["Enterprise Software", "Mobile Apps", "Custom APIs"],
            "website": "https://www.byteforge.de",
            "image": "https://images.unsplash.com/photo-1537432376769-00a5f6b7cc9c?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 14,
            "name": "EcoDrive Motors",
            "industry": "Automobile",
            "founded": 2015,
            "employees": 900,
            "headquarters": { "city": "Tokyo", "country": "Japan" },
            "contact": { "email": "info@ecodrive.jp", "phone": "+81-3-5550-2222" },
            "services": ["Electric Vehicles", "Battery Tech", "Mobility Solutions"],
            "website": "https://www.ecodrive.jp",
            "image": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 15,
            "name": "NextGen Robotics",
            "industry": "Robotics",
            "founded": 2016,
            "employees": 220,
            "headquarters": { "city": "Boston", "country": "USA" },
            "contact": { "email": "info@nextgenrobotics.com", "phone": "+1-617-555-0911" },
            "services": ["Industrial Automation", "AI Robotics", "R&D Prototyping"],
            "website": "https://www.nextgenrobotics.com",
            "image": "https://images.unsplash.com/photo-1581091226825-c6a4c9b48b04?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 16,
            "name": "CloudScale Data",
            "industry": "Cloud Computing",
            "founded": 2011,
            "employees": 600,
            "headquarters": { "city": "Dublin", "country": "Ireland" },
            "contact": { "email": "sales@cloudscale.ie", "phone": "+353-1-555-2234" },
            "services": ["Cloud Hosting", "Data Warehousing", "DevOps Tools"],
            "website": "https://www.cloudscale.ie",
            "image": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 17,
            "name": "VividDesign Studio",
            "industry": "Design & UX",
            "founded": 2014,
            "employees": 80,
            "headquarters": { "city": "Paris", "country": "France" },
            "contact": { "email": "hello@vividdesign.fr", "phone": "+33-1-555-0002" },
            "services": ["UI/UX Design", "Brand Identity", "Product Prototyping"],
            "website": "https://www.vividdesign.fr",
            "image": "https://images.unsplash.com/photo-1507209696998-3c532be9b2b8?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 18,
            "name": "InnoPharm Labs",
            "industry": "Pharmaceuticals",
            "founded": 2003,
            "employees": 740,
            "headquarters": { "city": "Zurich", "country": "Switzerland" },
            "contact": { "email": "info@innopharm.ch", "phone": "+41-44-555-1200" },
            "services": ["Drug Research", "Clinical Trials", "Bioinformatics"],
            "website": "https://www.innopharm.ch",
            "image": "https://images.unsplash.com/photo-1581093458791-9b6f3cbb8385?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 19,
            "name": "Oceanic Shipping Co.",
            "industry": "Maritime Transport",
            "founded": 1998,
            "employees": 1300,
            "headquarters": { "city": "Rotterdam", "country": "Netherlands" },
            "contact": { "email": "support@oceanicshipping.nl", "phone": "+31-10-555-7890" },
            "services": ["Cargo Shipping", "Port Operations", "Marine Logistics"],
            "website": "https://www.oceanicshipping.nl",
            "image": "https://images.unsplash.com/photo-1506619216599-9d16d0903dfd?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 20,
            "name": "MetroTech Electronics",
            "industry": "Electronics Manufacturing",
            "founded": 2007,
            "employees": 540,
            "headquarters": { "city": "Seoul", "country": "South Korea" },
            "contact": { "email": "sales@metrotech.kr", "phone": "+82-2-555-1234" },
            "services": ["Consumer Electronics", "Circuit Design", "Smart Devices"],
            "website": "https://www.metrotech.kr",
            "image": "https://images.unsplash.com/photo-1581091215367-59ab6b28f7f9?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 21,
            "name": "BioHarvest Foods",
            "industry": "Food & Beverage",
            "founded": 2012,
            "employees": 300,
            "headquarters": { "city": "Madrid", "country": "Spain" },
            "contact": { "email": "info@bioharvest.es", "phone": "+34-91-555-9988" },
            "services": ["Organic Foods", "Food Processing", "Nutritional Research"],
            "website": "https://www.bioharvest.es",
            "image": "https://images.unsplash.com/photo-1565958011705-44e211c2f3e2?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 22,
            "name": "DataMinds AI",
            "industry": "Artificial Intelligence",
            "founded": 2020,
            "employees": 150,
            "headquarters": { "city": "San Francisco", "country": "USA" },
            "contact": { "email": "team@dataminds.ai", "phone": "+1-415-555-2345" },
            "services": ["Machine Learning", "Data Engineering", "AI Automation"],
            "website": "https://www.dataminds.ai",
            "image": "https://images.unsplash.com/photo-1555949963-aa79dcee981d?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 23,
            "name": "UrbanHive Co-Labs",
            "industry": "Real Estate",
            "founded": 2015,
            "employees": 95,
            "headquarters": { "city": "New York", "country": "USA" },
            "contact": { "email": "support@urbanhive.com", "phone": "+1-212-555-0078" },
            "services": ["Co-working Spaces", "Property Leasing", "Smart Offices"],
            "website": "https://www.urbanhive.com",
            "image": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 24,
            "name": "EcoSphere Recycling",
            "industry": "Environmental Services",
            "founded": 2013,
            "employees": 220,
            "headquarters": { "city": "Copenhagen", "country": "Denmark" },
            "contact": { "email": "contact@ecosphere.dk", "phone": "+45-33-555-1020" },
            "services": ["Recycling Solutions", "Waste Management", "Sustainability Consulting"],
            "website": "https://www.ecosphere.dk",
            "image": "https://images.unsplash.com/photo-1615811361370-6b99b66ba04b?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 25,
            "name": "SmartGrid Utilities",
            "industry": "Energy",
            "founded": 2009,
            "employees": 370,
            "headquarters": { "city": "Melbourne", "country": "Australia" },
            "contact": { "email": "info@smartgrid.com.au", "phone": "+61-3-5550-9900" },
            "services": ["Power Distribution", "Smart Metering", "Grid Automation"],
            "website": "https://www.smartgrid.com.au",
            "image": "https://images.unsplash.com/photo-1509395054221-4195588b20f4?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 26,
            "name": "NovaTravel Group",
            "industry": "Travel & Hospitality",
            "founded": 2011,
            "employees": 160,
            "headquarters": { "city": "Lisbon", "country": "Portugal" },
            "contact": { "email": "care@novatravel.pt", "phone": "+351-21-555-3333" },
            "services": ["Tours", "Hotel Booking", "Travel Consulting"],
            "website": "https://www.novatravel.pt",
            "image": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 27,
            "name": "FusionWear Apparel",
            "industry": "Fashion & Retail",
            "founded": 2016,
            "employees": 280,
            "headquarters": { "city": "Milan", "country": "Italy" },
            "contact": { "email": "sales@fusionwear.it", "phone": "+39-02-555-0909" },
            "services": ["Sportswear", "E-commerce", "Sustainable Fashion"],
            "website": "https://www.fusionwear.it",
            "image": "https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 28,
            "name": "NextWave Telecom",
            "industry": "Telecommunications",
            "founded": 2004,
            "employees": 900,
            "headquarters": { "city": "Stockholm", "country": "Sweden" },
            "contact": { "email": "info@nextwave.se", "phone": "+46-8-555-1000" },
            "services": ["Mobile Networks", "Internet Services", "5G Deployment"],
            "website": "https://www.nextwave.se",
            "image": "https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 29,
            "name": "CodeSphere Labs",
            "industry": "Software & IT",
            "founded": 2018,
            "employees": 220,
            "headquarters": { "city": "Hyderabad", "country": "India" },
            "contact": { "email": "team@codesphere.in", "phone": "+91-40-55590909" },
            "services": ["Full Stack Development", "SaaS Platforms", "API Design"],
            "website": "https://www.codesphere.in",
            "image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 30,
            "name": "AeroLink Drones",
            "industry": "Aerial Services",
            "founded": 2021,
            "employees": 60,
            "headquarters": { "city": "Helsinki", "country": "Finland" },
            "contact": { "email": "contact@aerolink.fi", "phone": "+358-9-555-8899" },
            "services": ["Drone Mapping", "Aerial Inspection", "Photography"],
            "website": "https://www.aerolink.fi",
            "image": "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 31,
            "name": "PixelForge Games",
            "industry": "Gaming",
            "founded": 2013,
            "employees": 180,
            "headquarters": { "city": "Montreal", "country": "Canada" },
            "contact": { "email": "dev@pixelforge.ca", "phone": "+1-514-555-1222" },
            "services": ["Game Development", "3D Animation", "Publishing"],
            "website": "https://www.pixelforge.ca",
            "image": "https://images.unsplash.com/photo-1600083221882-6995b4c7e2cf?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 32,
            "name": "BrightMind Consulting",
            "industry": "Business Consulting",
            "founded": 2006,
            "employees": 340,
            "headquarters": { "city": "Chicago", "country": "USA" },
            "contact": { "email": "info@brightmind.com", "phone": "+1-312-555-4567" },
            "services": ["Business Strategy", "Operations", "Market Research"],
            "website": "https://www.brightmind.com",
            "image": "https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 33,
            "name": "SafeHome Automation",
            "industry": "Smart Home Tech",
            "founded": 2019,
            "employees": 95,
            "headquarters": { "city": "Austin", "country": "USA" },
            "contact": { "email": "support@safehome.io", "phone": "+1-512-555-7890" },
            "services": ["Home Security", "IoT Devices", "Voice Automation"],
            "website": "https://www.safehome.io",
            "image": "https://images.unsplash.com/photo-1599423300746-b62533397364?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 34,
            "name": "AgileEdge Technologies",
            "industry": "IT Services",
            "founded": 2010,
            "employees": 510,
            "headquarters": { "city": "Bangalore", "country": "India" },
            "contact": { "email": "care@agileedge.in", "phone": "+91-80-555-0022" },
            "services": ["Software Consulting", "Cloud Infrastructure", "Testing Services"],
            "website": "https://www.agileedge.in",
            "image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 35,
            "name": "HelioSpace Research",
            "industry": "Aerospace",
            "founded": 2017,
            "employees": 270,
            "headquarters": { "city": "Houston", "country": "USA" },
            "contact": { "email": "info@heliospace.org", "phone": "+1-281-555-4400" },
            "services": ["Space Research", "Launch Systems", "Satellite Design"],
            "website": "https://www.heliospace.org",
            "image": "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 36,
            "name": "CloudPath Solutions",
            "industry": "Software as a Service",
            "founded": 2020,
            "employees": 180,
            "headquarters": { "city": "Dubai", "country": "UAE" },
            "contact": { "email": "hello@cloudpath.io", "phone": "+971-4-555-3300" },
            "services": ["CRM Software", "Automation", "Cloud Hosting"],
            "website": "https://www.cloudpath.io",
            "image": "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 37,
            "name": "VistaGeo Mapping",
            "industry": "GIS & Geospatial",
            "founded": 2014,
            "employees": 140,
            "headquarters": { "city": "Delhi", "country": "India" },
            "contact": { "email": "info@vistageo.in", "phone": "+91-11-555-2345" },
            "services": ["GIS Mapping", "Spatial Analysis", "3D Visualization"],
            "website": "https://www.vistageo.in",
            "image": "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 38,
            "name": "MedixCare Labs",
            "industry": "Biotechnology",
            "founded": 2012,
            "employees": 430,
            "headquarters": { "city": "Basel", "country": "Switzerland" },
            "contact": { "email": "contact@medixcare.ch", "phone": "+41-61-555-6677" },
            "services": ["Diagnostics", "Gene Therapy", "Bio Research"],
            "website": "https://www.medixcare.ch",
            "image": "https://images.unsplash.com/photo-1581093588401-22f8579a68d1?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 39,
            "name": "SteelCore Manufacturing",
            "industry": "Industrial Manufacturing",
            "founded": 2005,
            "employees": 1100,
            "headquarters": { "city": "Pittsburgh", "country": "USA" },
            "contact": { "email": "sales@steelcore.com", "phone": "+1-412-555-5678" },
            "services": ["Steel Production", "Machinery Parts", "Fabrication"],
            "website": "https://www.steelcore.com",
            "image": "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?auto=format&fit=crop&w=800&q=60"
        },
        
        {
            "id": 48,
            "name": "NextGen Robotics",
            "industry": "Robotics & Automation",
            "founded": 2019,
            "employees": 60,
            "headquarters": { "city": "Tokyo", "country": "Japan" },
            "contact": { "email": "info@nextgenrobotics.jp", "phone": "+81-3-5555-2233" },
            "services": ["Industrial Robots", "AI Automation", "Robotic Research"],
            "website": "https://www.nextgenrobotics.jp",
            "image": "https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 49,
            "name": "SkyFleet Airlines",
            "industry": "Aviation",
            "founded": 2003,
            "employees": 1200,
            "headquarters": { "city": "Doha", "country": "Qatar" },
            "contact": { "email": "info@skyfleet.qa", "phone": "+974-4-555-2200" },
            "services": ["Passenger Flights", "Cargo Services", "Aircraft Leasing"],
            "website": "https://www.skyfleet.qa",
            "image": "https://images.unsplash.com/photo-1504198453319-5ce911bafcde?auto=format&fit=crop&w=800&q=60"
        },
        {
            "id": 50,
            "name": "EcoWare Solutions",
            "industry": "Environmental Services",
            "founded": 2017,
            "employees": 110,
            "headquarters": { "city": "Cape Town", "country": "South Africa" },
            "contact": { "email": "contact@ecoware.co.za", "phone": "+27-21-555-4411" },
            "services": ["Recycling Systems", "Sustainable Packaging", "Waste Management"],
            "website": "https://www.ecoware.co.za",
            "image": "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=800&q=60"
        }
    ]
}


export default CentralHub;